version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: calendar-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: huyho2004
      MYSQL_DATABASE: calendar_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - calendar-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: calendar-backend
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/calendar_app?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: huyho2004
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: service.ohayoucinema@gmail.com
      SPRING_MAIL_PASSWORD: tictgqrdumfdwyip
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      TZ: Asia/Ho_Chi_Minh
      SPRING_JPA_HIBERNATE_DDL-AUTO: none
      HOST: 0.0.0.0
    restart: always
    networks:
      - calendar-network

networks:
  calendar-network:
    driver: bridge

volumes:
  mysql-data:
